{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.configMap.name | default ( include "app-everton.fullname" . ) }}
    labels:
        {{- include "app-everton.labels" . | nindent 8 }}
{{- with .Values.configMap.data }}
data:
    {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
